### ISSUE TITLE
led-matrix does not work under Ubuntu -- switch from pynput to maybe keyboard module

### ISSUE THREAD

**Issue by sjjh** [MidnightJava/led-matrix#8]
I wanted to try out your `led-matrix` using `Ubuntu 24.04LTS` and get following error message:
```
Traceback (most recent call last):
  File "/home/user/src/led-matrix/./led_system_monitor.py", line 19, in <module>
    from pynput.keyboard import Key, Listener
ModuleNotFoundError: No module named 'pynput'
```
A web search revealed, `pynput` apparently not working under `Wayland`. A switch to `keyboard` module is recommended, cf. https://stackoverflow.com/questions/71828671/how-do-i-use-pynput-in-linux-or-is-pynput-not-working-on-linux/75496187#75496187 (even though `keyboard` seems to be unmaintained -- maybe there is even a better alternative?)

**Comment by timoteuszelle** [comment]
I will have a look later, not sure yet when I get to it, At least you know it's been seen.

**Comment by timoteuszelle** [comment]
Hi @sjjh,

Thank you for reporting this issue! I've implemented a fix that makes pynput optional and adds automatic fallback to evdev-only mode on Wayland systems.

Test Branch Available: I've created a test branch for you to try, since I don't have an Ubuntu/Wayland system to test on:

Branch: fix/wayland-pynput-optional-issue-8

Testing Instructions:

```
# Clone the test branch
git clone -b fix/wayland-pynput-optional-issue-8 https://github.com/timoteuszelle/led-matrix.git
cd led-matrix

# Install dependencies (without pynput to test the fix)
sudo apt update
sudo apt install -y python3-numpy python3-psutil python3-serial python3-evdev

# Run the application
python3 led_system_monitor.py
```

Expected Behavior

1. The application should start successfully without crashing
2. You should see a one-time info message: Info: pynput is unavailable; running in evdev-only mode. Use Ctrl+C to exit.
3. All monitoring features should work (CPU, memory, disk, network displays on LED panels)
4. Alt+I keyboard shortcut should still work (if you have proper permissions - see README for details)
5. Exit with Ctrl+C (ESC won't work in evdev-only mode)

What Changed

•  pynput is now optional on Linux - the app automatically falls back to evdev-only mode
•  Added clear user messages explaining the fallback
•  Updated README with Wayland compatibility notes and troubleshooting section
•  Maintained full backward compatibility (works normally when pynput is available)

Testing Checklist

Please test and report back on:
Application starts without errors
LED panels display system metrics correctly
Alt+I overlay works (if you have input group permissions)
Any warnings or unexpected behavior

If this works for you, I'll merge it to main and can also create a PR to the upstream repository if you'd like.

Thanks for testing!

**Comment by sjjh** [comment]
Thx for your work! Tried it:
- despite being member of the input group, keyboard access is not possible:
```
$ python3 led_system_monitor.py
top left cpu
bottom left mem-bat
top right disk
bottom right disk
left snap None
right snap None
Warning: Cannot access keyboard device for key listening: [Errno 13] Permission denied: '/dev/input/event7'
Key listener will be disabled. Use --no-key-listener to suppress this warning.
Found LED devices: Left: ('1-4.2:1.0', '/dev/ttyACM1'), Right: ('1-3.3:1.0', '/dev/ttyACM0')
^C
$ groups $USER
u : u adm dialout cdrom sudo dip video plugdev users input render lpadmin
$ ls -l /dev/input/event7 
crw-rw---- 1 root input 13, 71 Jan  5 19:28 /dev/input/event7
```
- thus(?) no info message about `pynput is unavailable`
- running with `sudo`, no error message about missing permission for keyboard and info message `pynput is unavailable` is shown
- but `ALT` + `I` seems to have no effect (only `[^i` is output)

**Comment by timoteuszelle** [comment]
I've implemented the fix for pynput/Wayland compatibility on this branch:
https://github.com/timoteuszelle/led-matrix/tree/fix/wayland-pynput-optional-issue-8

The implementation makes pynput optional and falls back to evdev-only mode when pynput is unavailable.

@sjjh You can test this by cloning from my fork:
```bash
git clone https://github.com/timoteuszelle/led-matrix.git
cd led-matrix
git checkout fix/wayland-pynput-optional-issue-8
# Install dependencies (evdev should work on Ubuntu/Wayland)
pip install evdev numpy pyserial
# Run without pynput
./led_system_monitor.py
```

The program should now run without pynput installed, using evdev for keyboard monitoring. Let me know if this works on Ubuntu 24.04 with Wayland!

**Comment by timoteuszelle** [comment]
I've pushed an improvement that auto-detects the keyboard device instead of hardcoding event7! 

**Please pull the latest changes:**
```bash
cd led-matrix
git pull origin fix/wayland-pynput-optional-issue-8-rebased
```

The new version will:
1. Automatically scan `/dev/input/event*` to find your keyboard
2. Print which device it's using (e.g., "Using keyboard device: /dev/input/event3")
3. Provide helpful error messages if permissions are needed

**If you get a permission error**, add your user to the `input` group:
```bash
sudo usermod -a -G input $USER
```
Then **log out and log back in** for the group change to take effect.

After that, the Alt+I combo should work with evdev! Let me know how it goes.

**Comment by MidnightJava** [comment]
I Integrated your fixes with my feature branch and merged it to main. The
merge commit message is pasted below. There may be some implications for
Windows and NixOS, since I don't have a Windows system to test, and I'm not
familiar with NixOS.

Specifically:
1. I use pyinstaller now to create an executable file that is run as a
service. In the pyinstaller build command I specify data files or
folders (e.g. config.yaml, plugins, et al) that are to be copied to the
executable directory. There are a number of nixos files in the repo, and I
don't know if any of these need to be copied to the executable directory.
If so, it's easy to add them, so please let me know.
2. Based on my experience on a Windows system a couple years ago, I think
pyinstaller works a little differently with Windows. Let me know if you see
any problems there (if you have Windows). Also for NixOS for that matter.

Summary of changes:

* Assignment of apps to quadrants is now handled by a config file
(config.yaml) rather than via program arguments
* Multiple apps can be assigned to any quadrant. The program will cycle
through them according to duration times specified in the config file
(previously, only the snapshot app could be run at specified intervals)
*  Apps can be run with a yaml config file
* LED panel animation (scrolling) by enabling this in the config file.
*  The keyboard device is automatically detected. It was previously
hard-coded, but auto-detection is needed because the device assignment can
change, particularly after keyboard firmware updates.
* Service installation is more robust and hardened. Previously, the service
ran under the user account, and it executed a script in the code
repository. Now it runs under a system account (no login permitted), and it
runs an executable file built by pyinstaller and installed to the /opt
directory.
*  Additional patterns added for the snapshot app

**Comment by timoteuszelle** [comment]
## ✅ Issue Resolved - Wayland Fixes Merged Upstream

### Status

Both Wayland compatibility fixes have been **successfully merged into upstream main**! 🎉

**What was fixed**:
- ✅ Optional pynput import (graceful fallback for Wayland)
- ✅ Keyboard auto-detection (no more hardcoded `/dev/input/event7`)

Merged in commit [f754a80](https://github.com/MidnightJava/led-matrix/commit/f754a80)

### For Ubuntu/Wayland Users

The fix is now available in upstream. Simply update:
```bash
git pull origin main
```

Confirmed working on Ubuntu 24.04 LTS with Wayland ✓

### Additional Contribution

I've also submitted **PR #10** with NixOS packaging updates to support the new yaml-config system. This is separate from the Wayland fix and provides declarative configuration support for NixOS users.

---

**This issue is resolved and can be closed** ✓

Thanks @MidnightJava for incorporating the fixes and the excellent yaml-config work!

**Comment by timoteuszelle** [comment]
> Also, FYI I plan to
> update the animate feature to support breathing as well as scrolling, and I
> have a couple ideas for additional apps, probably a time/temp display and a
> scrolling text message.
> […](#)

I already had some ideas and started to work on them: https://github.com/timoteuszelle/led-matrix/blob/feature/animation-library/ICON_SYSTEM_STATUS.md 
Just some idea's I had for a couple of weeks and started to get some concepts down. Let me know what you think.

**Comment by sjjh** [comment]
@MidnightJava @timoteuszelle Thanks for your work! I tried to use the new version, but running the installation script it failed to create the `systemd` service:

```
$ ./build_and_install.sh 
Detected Ubuntu/Debian system, installing dependencies with apt...
OK:1 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_24.04  InRelease
OK:2 https://updates.signal.org/desktop/apt xenial InRelease                   
OK:3 https://ppa.launchpadcontent.net/gnucash/ppa/ubuntu noble InRelease       
OK:4 https://repo.radeon.com/amdgpu/6.4.2/ubuntu noble InRelease               
OK:5 https://ppa.launchpadcontent.net/inkscape.dev/stable/ubuntu noble InRelease
Holen:6 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]    
OK:7 https://ppa.launchpadcontent.net/libreoffice/ppa/ubuntu noble InRelease   
OK:8 https://ppa.launchpadcontent.net/pbek/qownnotes/ubuntu noble InRelease    
OK:9 http://archive.ubuntu.com/ubuntu noble InRelease                          
OK:10 https://repo.radeon.com/rocm/apt/6.4.2 noble InRelease                   
Holen:11 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]     
Holen:12 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Holen:13 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [1.397 kB]
Holen:14 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [1.690 kB]
Holen:15 http://archive.ubuntu.com/ubuntu noble-updates/main Translation-en [312 kB]
Holen:16 http://security.ubuntu.com/ubuntu noble-security/main Translation-en [227 kB]
Holen:17 http://security.ubuntu.com/ubuntu noble-security/main amd64 Components [21,5 kB]
Holen:18 http://security.ubuntu.com/ubuntu noble-security/main amd64 c-n-f Metadata [9.660 B]
Holen:19 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Components [212 B]
Holen:20 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [920 kB]
Holen:21 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Components [175 kB]
Holen:22 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Packages [2.418 kB]
Holen:23 http://security.ubuntu.com/ubuntu noble-security/universe Translation-en [208 kB]
Holen:24 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Components [71,4 kB]
Holen:25 http://security.ubuntu.com/ubuntu noble-security/universe amd64 c-n-f Metadata [19,6 kB]
Holen:26 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Components [212 B]
Holen:27 http://archive.ubuntu.com/ubuntu noble-updates/restricted Translation-en [551 kB]
Holen:28 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Components [212 B]
Holen:29 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [1.510 kB]
Holen:30 http://archive.ubuntu.com/ubuntu noble-updates/universe Translation-en [307 kB]
Holen:31 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Components [377 kB]
Holen:32 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Components [940 B]
Holen:33 http://archive.ubuntu.com/ubuntu noble-backports/main amd64 Components [7.304 B]
Holen:34 http://archive.ubuntu.com/ubuntu noble-backports/restricted amd64 Components [216 B]
Holen:35 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Components [10,5 kB]
Holen:36 http://archive.ubuntu.com/ubuntu noble-backports/multiverse amd64 Components [212 B]
Es wurden 10,6 MB in 2 s geholt (5.622 kB/s).                     
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Aktualisierung für 26 Pakete verfügbar. Führen Sie »apt list --upgradable« aus, um sie anzuzeigen.
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
python3-numpy ist schon die neueste Version (1:1.26.4+ds-6ubuntu1).
python3-psutil ist schon die neueste Version (5.9.8-2build2).
python3-serial ist schon die neueste Version (3.5-2).
python3-evdev ist schon die neueste Version (1.7.0+dfsg-1build1).
Die folgenden zusätzlichen Pakete werden installiert:
  python3-xlib
Vorgeschlagene Pakete:
  python3-pynput-doc
Die folgenden NEUEN Pakete werden installiert:
  python3-pynput python3-xlib
0 aktualisiert, 2 neu installiert, 0 zu entfernen und 26 nicht aktualisiert.
Es müssen 177 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 1.057 kB Plattenplatz zusätzlich benutzt.
Holen:1 http://archive.ubuntu.com/ubuntu noble/universe amd64 python3-xlib all 0.33-2 [120 kB]
Holen:2 http://archive.ubuntu.com/ubuntu noble/universe amd64 python3-pynput all 1.7.6-1 [56,9 kB]
Es wurden 177 kB in 0 s geholt (804 kB/s).
Vormals nicht ausgewähltes Paket python3-xlib wird gewählt.
(Lese Datenbank ... 380166 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../python3-xlib_0.33-2_all.deb ...
Entpacken von python3-xlib (0.33-2) ...
Vormals nicht ausgewähltes Paket python3-pynput wird gewählt.
Vorbereitung zum Entpacken von .../python3-pynput_1.7.6-1_all.deb ...
Entpacken von python3-pynput (1.7.6-1) ...
python3-xlib (0.33-2) wird eingerichtet ...
python3-pynput (1.7.6-1) wird eingerichtet ...
./build_and_install.sh: Zeile 2: pyinstaller: Befehl nicht gefunden
+ dsp=:0
+ args=
+ sudo rm -f /etc/systemd/system/fwledmonitor.service
+ sudo tee /etc/systemd/system/fwledmonitor.service
+ id -u led_mon
+ sudo mkdir -p /opt/led_mon
+ sudo chown -R root /opt/led_mon
+ sudo chmod -R 755 /opt/led_mon
+ sudo rm -rf '/opt/led_mon/*'
+ sudo cp -r './dist/led_mon/*' /opt/led_mon/
cp: Aufruf von stat für './dist/led_mon/*' nicht möglich: Datei oder Verzeichnis nicht gefunden
+ sudo ln -sf /opt/led_mon/led_mon /usr/local/bin/led_mon
+ sudo systemctl daemon-reload
+ sudo systemctl stop fwledmonitor.service
+ sudo systemctl enable --now fwledmonitor.service
Job for fwledmonitor.service failed because the control process exited with error code.
See "systemctl status fwledmonitor.service" and "journalctl -xeu fwledmonitor.service" for details.
```
Truncated output of `journalctl -xeu fwledmonitor.service`:
```
Jan 08 22:39:16 laptop systemd[1]: Starting fwledmonitor.service - Framework 16 LED System Monitor...
░░ Subject: A start job for unit fwledmonitor.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit fwledmonitor.service has begun execution.
░░ 
░░ The job identifier is 30359.
Jan 08 22:39:16 laptop xhost[68133]: Authorization required, but no authorization protocol specified
Jan 08 22:39:16 laptop xhost[68133]: /usr/bin/xhost:  unable to open display ":0"
Jan 08 22:39:16 laptop systemd[1]: fwledmonitor.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStartPre= process belonging to unit fwledmonitor.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Jan 08 22:39:16 laptop systemd[1]: fwledmonitor.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit fwledmonitor.service has entered the 'failed' state with result 'exit-code'.
Jan 08 22:39:16 laptop systemd[1]: Failed to start fwledmonitor.service - Framework 16 LED System Monitor.
░░ Subject: A start job for unit fwledmonitor.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit fwledmonitor.service has finished with a failure.
░░ 
░░ The job identifier is 30359 and the job result is failed.
Jan 08 22:39:16 laptop systemd[1]: fwledmonitor.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ Automatic restarting of the unit fwledmonitor.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
```

**Comment by sjjh** [comment]
It is [suggested](https://askubuntu.com/questions/1543511/pyinstaller-failed-install-ubuntu-24-04-lts) to install the package `python3-pyinstaller`, but it seems not to be in the repository (Ubuntu 24.04 LTS).

**Comment by sjjh** [comment]
https://pyinstaller.org/en/stable/installation.html suggests to use `pip` to install it.

**Comment by sjjh** [comment]
Seems not to work for me because of python environment setup...:

```
$ pip3 install --user pyinstaller
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by MidnightJava** [comment]
@timoteuszelle Thanks for fixoing those installation issues. I failed to test the install from scratch after adding pyinstaller, I think.

@sjjh To get past the issue you reported, I made the following change in install_deps.sh

change pip3 install --user pyinstaller

to

python -m pip install pyinstaller

Even without --user, pip3 install did not work for me. Not sure why, but running pip as a module worked.

**Comment by sjjh** [comment]
> python -m pip install pyinstaller

That still does not work for me, the command `python` is not known, only `python3`. If I use `python3`, I end up with the same error message:
```
$ python -m pip install pyinstaller
Der Befehl 'python' wurde nicht gefunden, meinten Sie:
  Befehl 'python3' aus dem deb python3
  Befehl 'python' aus dem deb python-is-python3
$ python3 -m pip install pyinstaller
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
What does work for me, is running `pipx install pyinstaller`. But then the module is still not available:
```
$ python3 -m PyInstaller --onedir --name led_mon --add-data plugins:plugins --    add-data snapshot_files:snapshot_files --add-data config.yaml:. --hidden-imp    ort=yaml --hidden-import=pynput --clean --noconfirm main.py
/usr/bin/python3: No module named PyInstaller
```

**Comment by MidnightJava** [comment]
I think python is just an alias of python3 for convenience, so I would expect python3 to work. The problem may be that the module name is all lower case. Please try `python3 -m pyinstaller...` and let me know how that works.

EDIT: Also, are you running in a virual environment? I think maybe not, since python is not aliased to python3. I'm unable to get the installation to work unless I use a virtual env. I'm on Ubuntu 24.04 (Pop!_OS to be more precise). What OS are you using?

**Comment by MidnightJava** [comment]
I think the lack of virtual env is causing the failure. I get the same result when I run without one. Follow this from the README:

Install pyenv from [here](https://github.com/pyenv/pyenv). Follow the instructions for installing deps and then pyenv.

Then run:
pyenv install 3.11 # or higher (tested up to 3.14)
pyenv virtualenv 3.11 led-matrix-env
pyenv activate led-matrix-env

I ran with 3.11 for a while and am now running with 3.14. We're essentially on the same OS. PoP!_OS is system76's OS based on Ubuntu, mostly geared toward system76 hardware which I used to have, as well as Cosmic desktop and their own app store, etc, none of which I think is relevant to the issue you're having.

**Comment by sjjh** [comment]
I had to change `python` to `python3` (see PRs), but still fail to install because of the `virt env` issue. I have not tested your recommendations from https://github.com/MidnightJava/led-matrix/issues/8#issuecomment-3730677445 yet due to missing time. But coming back to

> A virtual env is not necessarily required. It turns out to be required for Ubuntu 24.04

I'd say, the `build_and_install.sh` and the `readme.md` should probably take it into account. At least I would have been lost without your support and it wasted already quite some time of you to help me get it up an running. I would suggest: If possible, the script should set everything up to just run it (under Ubuntu 24.04 LTS), if not possible, at least inform about the issue, cancel the installation and point to the readme.

**Comment by sjjh** [comment]
So, I tried to follow the instructions given in `readme.md` and in your comment to set up the `virtual environment`, but fail again:
```
$ pyenv install 3.14
Downloading Python-3.14.2.tar.xz...
-> https://www.python.org/ftp/python/3.14.2/Python-3.14.2.tar.xz
Installing Python-3.14.2...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import bz2
  File "/home/simon/.pyenv/versions/3.14.2/lib/python3.14/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import ctypes
  File "/home/simon/.pyenv/versions/3.14.2/lib/python3.14/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import ssl
  File "/home/simon/.pyenv/versions/3.14.2/lib/python3.14/ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ModuleNotFoundError: No module named '_ssl'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 24.04 using python-build 2.6.18)

Inspect or clean up the working tree at /tmp/python-build.20260111230501.28564
Results logged to /tmp/python-build.20260111230501.28564.log

Last 10 log lines:
	LD_LIBRARY_PATH=/tmp/python-build.20260111230501.28564/Python-3.14.2 ./python -E -m ensurepip \
		$ensurepip --root=/ ; \
fi
WARNING: Disabling truststore since ssl support is missing
Looking in links: /tmp/tmp4fauc8ui
Processing /tmp/tmp4fauc8ui/pip-25.3-py3-none-any.whl
Installing collected packages: pip
  WARNING: The scripts pip3 and pip3.14 are installed in '/home/simon/.pyenv/versions/3.14.2/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-25.3
$ pyenv virtualenv 3.14 led-matrix-env
pyenv-virtualenv: `3.14' is not installed in pyenv.
It does not look like a valid Python version. See `pyenv install --list' for available versions.
$ pyenv install --list | grep '3.14'
  3.14.0
  3.14.0t
  3.14-dev
  3.14t-dev
  3.14.1
  3.14.1t
  3.14.2
  3.14.2t
  miniconda2-4.3.14
  miniconda3-4.3.14
  pypy2.7-7.3.14-src
  pypy2.7-7.3.14
  pypy3.9-7.3.14-src
  pypy3.9-7.3.14
  pypy3.10-7.3.14-src
  pypy3.10-7.3.14
```

**Comment by MidnightJava** [comment]
> So, I tried to follow the instructions given in readme.md and in your comment to set up the virtual environment, but fail again:

I think you're missing the python deps that the pyenv sitre says you need before you try to install a pythin version. Click the link under step D on the pyenv site, and it takes you to the dependency installation page. For debian, it gives this line:

```
sudo apt update; sudo apt install make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev curl git \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
```

I don't mind helping you work through this. I don't think it's right to make the installation scripts handle the pyenv installation and config because that is not something I can determine ahead of time for people who will use the app. It would be like adding lines to install an IDE and configure it. This could theoretically be done, but it would fail for lots of people, and more importantly, people want to make their own choice about an IDE and how to configure it. I know pyenv is not as involved as an IDE, bu the point is it's a tool and not a library dependency.

**Comment by MidnightJava** [comment]
> I had to change python to python3 (see PRs)

I believe this was fixed bny the change I referenced above where I removed sudo from build_and_install.sh. That was an error on my part, and I think it was causing part of your problems. Because I was invoking the commands in install_deps.sh as sudo, none of them were running in the virtual environment.

**Comment by sjjh** [comment]
Finally managed to install it, and can run it from command line. Installing and running it as `systemd` service still fails. The readme mentions to install the dependencies with `sudo`, but this fails (even if I activate the `virt env` before).

> I don't think it's right to make the installation scripts handle the pyenv installation and config because that is not something I can determine ahead of time for people who will use the app. 

I do understand your point (and thanks for your willingness to get me through this!). Maybe the solution to my problem is something completely different. I'm just believing, the use-case of someone using Ubuntu 24.04 LTS and wanting to run *led-matrix* (as service) should be much easier as I'm experiencing it right now and should need much less of your time. Thus I'm wondering how to improve the readme/installer script in a way that a layman with Ubuntu 24.04 LTS is able to install and use (as a service) *led-matrix* on their own in a way as simple as possible.

**Comment by sjjh** [comment]
> Are you referring to this under Linux Service Dependencies?

Yes.

> Is the service installation still failing? If so, please post the output of journalctl -fu fwledmonitor.

Yes, see below:
```
$ journalctl -fu fwledmonitor
Jan 12 00:03:56 laptop systemd[1]: Starting fwledmonitor.service - Framework 16 LED System Monitor...
Jan 12 00:03:56 laptop xhost[66225]: Authorization required, but no authorization protocol specified
Jan 12 00:03:56 laptop xhost[66225]: /usr/bin/xhost:  unable to open display ":0"
Jan 12 00:03:56 laptop systemd[1]: fwledmonitor.service: Control process exited, code=exited, status=1/FAILURE
Jan 12 00:03:56 laptop systemd[1]: fwledmonitor.service: Failed with result 'exit-code'.
Jan 12 00:03:56 laptop systemd[1]: Failed to start fwledmonitor.service - Framework 16 LED System Monitor.
Jan 12 00:03:56 laptop systemd[1]: fwledmonitor.service: Scheduled restart job, restart counter is at 5.
Jan 12 00:03:56 laptop systemd[1]: fwledmonitor.service: Start request repeated too quickly.
Jan 12 00:03:56 laptop systemd[1]: fwledmonitor.service: Failed with result 'exit-code'.
Jan 12 00:03:56 laptop systemd[1]: Failed to start fwledmonitor.service - Framework 16 LED System Monitor.
```

**Comment by sjjh** [comment]
Running these as my normal user, with python virt env enabled.

> Run echo $DISPLAY and confirm that it's :0

Confirmed.

> Run xclock (apt-install if needed) and see if a clock gui is displayed.

Confirmed.

> try removing that ExecStartPre line form the service config and then run sudo systemctl daemon-reload && sudo systemctl restart fwledmonitor.

Still failing:
```
$ journalctl -fu fwledmonitor
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Main process exited, code=exited, status=203/EXEC
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Failed with result 'exit-code'.
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Scheduled restart job, restart counter is at 4.
Jan 12 01:56:14 laptop systemd[1]: Started fwledmonitor.service - Framework 16 LED System Monitor.
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Main process exited, code=exited, status=203/EXEC
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Failed with result 'exit-code'.
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Scheduled restart job, restart counter is at 5.
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Start request repeated too quickly.
Jan 12 01:56:14 laptop systemd[1]: fwledmonitor.service: Failed with result 'exit-code'.
Jan 12 01:56:14 laptop systemd[1]: Failed to start fwledmonitor.service - Framework 16 LED System Monitor.
```

**Comment by timoteuszelle** [comment]
@sjjh Thanks for the detailed error logs! The issue is that Ubuntu 24.04 has stricter Python package management (PEP 668) that prevents the PyInstaller-based installation from working without a virtual environment.

Since you already tested the application successfully from source (running `python3 led_system_monitor.py` directly), here's a simpler approach that doesn't require PyInstaller:

## Alternative Installation (No PyInstaller Required)

**1. Install system dependencies:**
```bash
sudo apt update
sudo apt install -y python3-numpy python3-psutil python3-serial python3-evdev python3-pynput python3-yaml
```

**2. Clone the repository (if you haven't already):**
```bash
git clone https://github.com/MidnightJava/led-matrix.git
cd led-matrix
```

**3. Run directly from source:**
```bash
python3 led_system_monitor.py
```

This should work on your system since you've already confirmed it runs successfully.

## Optional: Set up as a systemd service (without PyInstaller)

If you want it to run as a service, create a simple service file:

```bash
sudo tee /etc/systemd/system/fwledmonitor.service > /dev/null <<EOF
[Unit]
Description=Framework 16 LED System Monitor
After=network.service

[Service]
Type=simple
User=tim
Group=tim
WorkingDirectory=/home/tim/personal-git/led-matrix
ExecStart=/usr/bin/python3 /home/tim/personal-git/led-matrix/led_system_monitor.py -cf /home/tim/personal-git/led-matrix/config.yaml
Restart=always

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now fwledmonitor.service
```

**Check status:**
```bash
sudo systemctl status fwledmonitor.service
```

Let me know if this works for you. If it does, we can update the installation script to better handle Ubuntu 24.04's restrictions.

**Comment by sjjh** [comment]
deleting the user, rerunning `install_service.sh` (exiting with the same issue as before, that the service cannot start)
```
$ id -u led_mon
997
$ groups led_mon
led_mon : led_mon dialout
$ sudo usermod -a -G input led_mon
$ groups led_mon
led_mon : led_mon dialout input
$ sudo systemctl daemon-reload
$ sudo systemctl stop fwledmonitor.service
$ sudo systemctl enable --now fwledmonitor.service
Job for fwledmonitor.service failed because the control process exited with error code.
See "systemctl status fwledmonitor.service" and "journalctl -xeu fwledmonitor.service" for details.
Jan 12 23:38:46 laptop systemd[1]: Starting fwledmonitor.service - Framework 16 LED System Monitor...
░░ Subject: A start job for unit fwledmonitor.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit fwledmonitor.service has begun execution.
░░ 
░░ The job identifier is 38412.
Jan 12 23:38:46 laptop xhost[68644]: Authorization required, but no authorization protocol specified
Jan 12 23:38:46 laptop xhost[68644]: /usr/bin/xhost:  unable to open display ":0"
Jan 12 23:38:46 laptop systemd[1]: fwledmonitor.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStartPre= process belonging to unit fwledmonitor.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
```
Maybe the `install_service.sh`-script needs to use `-G input,dialout` for the `useradd` -- but that seems not to be the main issue.

**Comment by sjjh** [comment]
> The usermod command can take multiple -G args or one -G with groups separated by commas with no spaces

Beside that fact, that the script uses `useradd` instead of `usermod`, the first group `input` was missing for my user, thus my assumption that something with this command did not work out as intended. `man` did specify the `-G g1,g2,g3` syntax, but not the `-G g1 -G g2` syntax (which still might not mean that you cannot use it)

In case it helps:
```
$ xauth list
laptop/unix:  MIT-MAGIC-COOKIE-1  49881b9d65510413e1b3b91d259c625c
#ffff#6c6170746f70#:  MIT-MAGIC-COOKIE-1  49881b9d65510413e1b3b91d259c625c
$ env | grep DISPLAY
WAYLAND_DISPLAY=wayland-0
GNOME_SETUP_DISPLAY=:1
DISPLAY=:0
$ env | grep XAUTHORITY
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.NJ9ZI3
$ ps aux | grep Xwayland
simon       6295  0.0  0.1 1121768 113956 ?      Sl   09:55   0:03 /usr/bin/Xwayland :0 -rootless -noreset -accessx -core -auth /run/user/1000/.mutter-Xwaylandauth.NJ9ZI3 -listenfd 4 -listenfd 5 -displayfd 6 -initfd 7 -byteswappedclients

```
> I thought we could just remove that ExecStartPre line and let the app fail to connect to the x-server, in which case the pynput import will fail and it fall back to evdev gracefully. I believe you tried that yesterday, and it did not work?

I lost a little track of what I tried in the last days, so just did it again. I removed the complete `ExecStartPre` line from the file and restarted the service, seems to run fine now:
```
$ journalctl -xeu fwledmonitor.service
Jan 13 00:04:19 laptop systemd[1]: Started fwledmonitor.service - Framework 16 LED System Monitor.
░░ Subject: A start job for unit fwledmonitor.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit fwledmonitor.service has finished successfully.
░░ 
░░ The job identifier is 40116.
Jan 13 00:04:19 laptop led_mon[72073]: 2026-01-13 00:04:19,397 DEBUG __main__: Calling main
Jan 13 00:04:19 laptop led_mon[72073]: 2026-01-13 00:04:19,399 INFO led_system_monitor: Using config file config.yaml
Jan 13 00:04:19 laptop led_mon[72073]: 2026-01-13 00:04:19,875 INFO led_system_monitor: Using keyboard device: /dev/input/event22
Jan 13 00:04:19 laptop led_mon[72073]: 2026-01-13 00:04:19,885 INFO led_system_monitor: Found LED devices: Left: ('1-4.2:1.0', '/dev/ttyACM1'), Right: ('1-3.3:1.0', >
Jan 13 00:04:19 laptop led_mon[72073]: 2026-01-13 00:04:19,928 WARNING led_system_monitor: Info: pynput is unavailable; running in evdev-only mode. Use Ctrl+C to ex
```

**Comment by MidnightJava** [comment]
OK, thanks for that info. Here is where I think we are:

1. You and I both see pynput unavailable. This is most likely caused by using wayland, but I would still expect it to work since Xwayland is running. It doesn't really mater, since pynput is there mostly for cross-platform compatibility (i.e. Windows)

2. On your system, the service fails to start if you include the ExecStartPre line. This does not happen for me, in two different Pop!_OS 24.04 instances running on the same hardware via dual-boot. I don't know why it fails for you, and I'm out of ideas. I'd like to leave the line in the service config, because I think it's needed to give any chance of pynput working, unless a user has explicitly added the permission. I'll keep an eye out for anyone else having the same problem, and maybe I'll add a note in the README about it.

Thanks for hanging in there and working through several issues with us. I already corrected some things based on your experience, and I will also update the README file to explain about virtual environments, as you suggested.

By all means, send us feature ideas, as well as any more feedback as needed.
